version: "3.3"
services:
  app:
      build: ./app
      restart: always
      container_name: app
      env_file:
        - ./app/env/development.env
      volumes:
        - ./app:/app
      links:
          - redis
      ports:
          - "5001:5001"
  redis:
    build: ./redis
    restart: on-failure
    container_name: redis
    volumes:
        - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
        - ./redis/data:/var/lib/redis
    ports:
        - "6379:6379"