version: "3.3"
services:
  app:
      build:
        context: ./app
        args:
          SERVERMODE : ""
      restart: always
      container_name: app
      env_file:
        - ./app/env/development.env
      volumes:
        - ./app:/app
      links:
          - redis_db
      ports:
          - "5000:5000"
  redis_db:
    build:
      context: ./redis
      args:
        ENVMODE : dev
    restart: on-failure
    container_name: redis_db
    volumes:
        - ./redis/config/redis-dev.conf:/usr/local/etc/redis/redis.conf
        - ./redis/data:/var/lib/redis
    ports:
        - "6379:6379"
