version: "3.3"
services:
  app:
      build:
        context: ./app
        args:
          SERVERMODE : "--reload"
      restart: always
      container_name: app
      env_file:
        - ./app/env/production.env
      volumes:
        - ./app:/app
      links:
          - redis_db
      ports:
          - "5000:5000"
  redis_db:
    build:
      context: ./redis
      args:
        ENVMODE : prod
    restart: always
    container_name: redis_db
    volumes:
        - ./redis/config/redis-prod.conf:/usr/local/etc/redis/redis.conf
        - ./redis/data:/data
    ports:
        - "6379:6379"